#!/bin/bash
pyenv local 3.6.10
eval "$(pyenv init -)"
python3.6 -m venv .venv
source activate
pip install --upgrade pip
pip install -r requirements.txt
pip install git+https://github.com/scikit-garden/scikit-garden
pip install git+https://gitlab.com/CEMRACS17/shapley-effects
